spring:
  application:
    # sets the name in Eureka & Zipkin
    name: ${springboot.app.name:weatherservice}

server:
  port: 8095

soap:
  service:
    base:
      url: /soap
  messages:
    logging: true
    extract: true

cxf:
  servicelist:
    title: WeatherService - Shine baby, shine!

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true
    # should imediately (1 sec) provide instance information changes
    instance-info-replication-interval-seconds: 1
  instance:
    # highest possible rate to send heartbeats to Eureka server to indicate it´s still alive
    # (needed because of the extreme fast lease-expiration-duration = 2 @ Eureka server)
    registry-fetch-interval-seconds: 1
    lease-renewal-interval-in-seconds: 1

# No ugly logging pollution, if Eureka isn´t up or found
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF