#jinja2: newline_sequence:'\r\n'
version: '3.1'

services:
 eureka-serviceregistry:
  build: ./eureka-serviceregistry
  ports:
   - "8761:8761"
  tty:
    true
 weatherbackend:
  build: ./weatherbackend
  ports:
   - "8090:8090"
  environment:
   - "REGISTRY_HOST=eureka-serviceregistry"
   - "REGISTRY_PORT=8761"
  tty:
    true
 zuul-edgeservice:
  build: ./zuul-edgeservice
  ports:
   - "8080:8080"
  depends_on:
   - eureka-serviceregistry
  environment:
   - "REGISTRY_HOST=eureka-serviceregistry"
   - "REGISTRY_PORT=8761"
  tty:
    true


networks:
 default:
  external:
   name: "nat"