server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    com:
      netflix:
        discovery: ERROR