server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    # sets the name in Eureka & Zipkin
    name: ${springboot.app.name:weatherbackend}
  zipkin:
    baseUrl: http://${zipkin.host:localhost}:9412/

logging:
  level:
    com:
      netflix:
        discovery: ERROR

# see all actuator data
management:
  security:
    enabled: false