server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true

spring:
  zipkin:
    baseUrl: http://${zipkin.host:localhost}:9411/

logging:
  level:
    com:
      netflix:
        discovery: ERROR