spring:
  application:
    # sets the name in Eureka
    name: ${springboot.app.name:eureka-serviceregistry}
  # show the actuator endpoints´ output in a formatted (prettier) way
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8761

eureka:
  instance:
    hostname: ${springboot.app.name:eureka-serviceregistry}
    # instantly (2sec) remove non-available apps from eureka
    lease-expiration-duration-in-seconds: 2
    # highest possible rate to send heartbeats to Eureka server to indicate it´s still alive
    # (needed because of the extreme fast lease-expiration-duration = 2 @ Eureka server)
    lease-renewal-interval-in-seconds: 1
  client:
    registerWithEureka: true
    # Eureka should always ask for instances at the other Eureka server and don´t cache them
    fetchRegistry: false
    # should imediately (1 sec) provide instance information changes
    instance-info-replication-interval-seconds: 1
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/

# make configuration information available through actuator endpoints
management:
  security:
    enabled: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF