spring:
  application:
    # sets the name in Eureka
    name: eureka-serviceregistry

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-serviceregistry
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-serviceregistry:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF