server:
  port: 8761

eureka:
  instance:
    hostname: eureka-serviceregistry
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-serviceregistry:${server.port}/eureka/

spring:
  zipkin:
    baseUrl: http://${zipkin.host:localhost}:9411/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF