server:
  port: 8080

zuul:
  prefix: /api
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

# Switch Eureka-Usage on & off
ribbon:
  eureka:
    enabled: enabled
  # see http://stackoverflow.com/questions/32113671/zuulproxy-fails-with-ribboncommand-timed-out-and-no-fallback-available-when-it
  # Connect timeout used by Apache HttpClient
  ConnectTimeout: 60000
  # Read timeout used by Apache HttpClient
  ReadTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    # sets the name in Eureka & Zipkin
    name: zuul-edgeservice
  zipkin:
    baseUrl: http://${zipkin.host:localhost}:9412/

logging:
  level:
    com:
      netflix:
        discovery: ERROR

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

# see all actuator data
management:
  security:
    enabled: false