spring:
  application:
    # sets the name in Eureka & Zipkin
    name: zuul-edgeservice
  zipkin:
    baseUrl: http://${zipkin.host:localhost}:9411/

server:
  port: 8080

zuul:
  prefix: /api

# Switch Eureka-Usage on & off
ribbon:
  eureka:
    enabled: enabled

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

# No ugly logging polution, if Eureka isn´t up or found
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF